# OSPF Config

---
  - hosts: r1
    gather_facts: false

    tasks:
      - name: Configuring OSPF
        ios_config:
          parents: "router ospf 10"
          lines:
            - network 172.16.46.205 0.0.0.0 area 1
            - network 1.1.1.0 0.255.255.255 area 1
  
  - hosts: r3
    gather_facts: false

    tasks:
      - name: Configure OSPF
        ios_config:
          parents: "router ospf 10"
          lines:
            - network 172.16.46.207 0.0.0.0 area 1
            - network 3.3.3.0 0.255.255.255 area 1


  - hosts: routers
    gather_facts: false

    tasks:
      - name: hsow ip interface
        ios_command:
          command:
            - show ip interface br




en
conf t
line vty 0 4
transport input all
login local
exit

crypto key generate rsa general-keys mod 1024

username admin priv 15 password cisco